name: "Version Bumper"
description: "Bumps semantic version based on PR labels and increments build number."

inputs:
  github_token:
    description: "Github Token"
    required: true
  version_file:
    description: "Path to pubspec file"
    required: true

outputs:
  new_version:
    description: "New semantic version generated"
    value: ${{ steps.output.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitHub CLI (gh)
      shell: bash
      run: |
        (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

    - name: Run version bump logic
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        VERSION_FILE: ${{ inputs.version_file }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
      run: |
        set -e

        echo "VERSION_FILE: $VERSION_FILE"
        echo "PR_NUMBER: $PR_NUMBER"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"

        # Skip entirely if it's a PR from staging -> main (before merge)
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_REF_NAME" == "staging" && "$GITHUB_BASE_REF" == "main" ]]; then
          echo "PR from staging to main detected; no version bump performed."
          exit 0
        fi

        git fetch --tags
        LATEST_TAG=$(git tag -l 'v*.*.*' --sort=-version:refname | head -n1)
        LATEST_TAG=${LATEST_TAG:-v0.0.0+0}
        echo "LATEST_TAG=$LATEST_TAG"

        SEMVER=${LATEST_TAG#v}
        SEMVER=${SEMVER%%-RC*}
        echo "Current version: $SEMVER"

        MAJOR=$(echo "$SEMVER" | cut -d '.' -f 1)
        MINOR=$(echo "$SEMVER" | cut -d '.' -f 2)
        PATCH=$(echo "$SEMVER" | cut -d '.' -f 3 | cut -d '+' -f 1)
        BUILD=$(echo "$SEMVER" | grep '+' | cut -d '+' -f 2)
        BUILD=${BUILD:-1}

        LABELS=""
        if [ -n "$PR_NUMBER" ]; then
          LABELS=$(gh pr view "$PR_NUMBER" --json labels -q '.labels[].name')
        fi

        BUMP_TYPE=""
        if echo "$LABELS" | grep -qi "major"; then
          BUMP_TYPE="major"
        elif echo "$LABELS" | grep -qi "minor"; then
          BUMP_TYPE="minor"
        elif echo "$LABELS" | grep -qi "patch"; then
          BUMP_TYPE="patch"
        else
          echo "No valid bump label found (major/minor/patch). Incrementing build number only."
        fi

        echo "Bump type identified: $BUMP_TYPE"

        case $BUMP_TYPE in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH + 1))
            ;;
          *)
            echo "Build number will increment only."
            ;;
        esac

        BUILD=$((BUILD + 1))

        NEW_SEMVER="$MAJOR.$MINOR.$PATCH"
        echo "new semver = $NEW_SEMVER"
        NEW_VERSION="${NEW_SEMVER}+${BUILD}"
        echo "new version = $NEW_VERSION"

        if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF_NAME" == "staging" ]]; then
          TAG_VERSION="v${NEW_SEMVER}-RC+${BUILD}"
          echo "Staging branch detected (push), tagging as RC: $TAG_VERSION"

        elif [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF_NAME" == "main" ]]; then
          TAG_VERSION="v${NEW_SEMVER}+${BUILD}"
          echo "Merged into main (push), finalizing tag: $TAG_VERSION"

        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_BASE_REF" == "main" && "$GITHUB_HEAD_REF" == "staging" ]]; then
          echo "PR from staging to main detected, no tagging yet."
          exit 0

        else
          TAG_VERSION="v${NEW_SEMVER}+${BUILD}"
          echo "Regular version bump: $TAG_VERSION"
        fi


        echo "tag version = $TAG_VERSION"

        # Update version file
        sed -i -E "s/^version:[[:space:]]*.*/version: ${NEW_VERSION}/" "$VERSION_FILE"
        echo "File updated with new version"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        echo "starting commit"

        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          gh auth setup-git

          git add "$VERSION_FILE"
          git commit -m "chore: bump version to ${TAG_VERSION#v}"
          git push origin HEAD

          git tag "$TAG_VERSION"
          git push origin "$TAG_VERSION"
        else
          echo "Pull request event detected; skipping commit/tag push."
        fi

        echo "new_version=${TAG_VERSION#v}" >> "$GITHUB_OUTPUT"
        echo "new_version=${TAG_VERSION#v}" >> "$GITHUB_ENV"
