###########################################
# AUTO COMMIT ACTION
###########################################
name: "Auto Commit Action"
description: "Automatically update version files and push changes."

inputs:
  pat_token:
    description: "Personal Access Token for authentication"
    required: true
  version_file:
    description: "Path to the version file"
    required: true
  branch:
    description: "Branch to push changes to"
    required: true
  new_version:
    description: "The new version after the update"
    required: true
  new_tag_version:
    description: "The new tag version after the update"
    required: true
  app_id:
    description: "GitHub App ID"
    required: true
  private_key:
    description: "GitHub App Private Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: ${{ github.ref_name != 'main' }}
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.pat_token }}
        ref: ${{ github.head_ref }} # feature branch
        # ref: ${{ github.ref_name }} # feature branch
        # ref: ${{ github.base_ref }} # develop branch

    - name: Update version file
      if: ${{ github.ref_name != 'main' }}
      shell: bash
      env:
        VERSION_FILE: ${{ inputs.version_file }}
        NEW_VERSION: ${{ inputs.new_version }}
      run: |
        sed -i -E "s/^version:[[:space:]]*.*/version: ${NEW_VERSION}/" "$VERSION_FILE"

    - name: Push tag for main branch
      if: ${{ github.ref_name == 'main' }}
      shell: bash
      env:
        tag_version: ${{ inputs.new_version }}
      run: |
        TAG_VERSION="v${tag_version}"
        git tag "$TAG_VERSION"
        git push origin "$TAG_VERSION"

      ###########################################
      # TOKENIZED AUTO COMMIT
      ###########################################
    - name: Get GitHub App Token
      id: auth
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}

    - uses: actions/checkout@v4
      with:
        token: ${{ steps.auth.outputs.token }}

    - name: Commit and Push Changes
      if: ${{ github.ref_name != 'main' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
        TAG_VERSION: ${{ inputs.new_tag_version }}
        BRANCH: ${{ inputs.branch }}
      run: |
        git config user.name "MyCommitBot"
        git config user.email "[email protected]"

        git fetch origin $BRANCH:$BRANCH
        git checkout $BRANCH

        git add .
        git commit -m "Automated commit"

        git push origin HEAD:$BRANCH

        if [ -z "$TAG_VERSION" ]; then
          echo "TAG_VERSION is not set. Skipping tag step."
        else
          git tag "$TAG_VERSION"
          git push origin "$TAG_VERSION"
        fi
