---
name: Develop Workflow

on:
  pull_request:
    branches:
      - "develop"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - closed
  workflow_dispatch:

concurrency:
  group: develop-versioning-and-build
  cancel-in-progress: false

jobs:
  version-build-firebase:
    name: Develop - Versioning, Building, and Firebase
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ###########################################
      # VERSION BUMP
      ###########################################
      - name: Bump version based on PR labels
        if: github.event.pull_request.merged == true
        id: version
        uses: ./.github/actions/version-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pat_token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          version_file: "version.txt"
          branch: "develop"

      ###########################################
      # TOKENIZED AUTO COMMIT
      ###########################################
      - name: New Commit
        if: github.event.pull_request.merged == true
        uses: ./.github/actions/auto-commit
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          version_file: "version.txt"
          new_version: ${{ steps.version.outputs.new_version }}
          new_tag_version: ${{ steps.version.outputs.new_tag_version }}
          branch: "develop"

      ###########################################
      # BUILD
      ###########################################
      - name: Build a new APK / AAP
        run: echo "Build"

      ###########################################
      # FIREBASE UPLOAD
      ###########################################
      - name: Firebase Upload
        if: github.event.pull_request.merged == true
        run: echo "Firebase Upload"
