---
name: Production Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

concurrency:
  group: production-versioning-and-build
  cancel-in-progress: false

jobs:
  version-build-prod:
    name: Production - Version Bump, Build, and Production
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ###########################################
      # VERSION BUMP
      ###########################################
      - name: Bump version based on PR labels
        if: github.event.pull_request.merged == true
        id: version
        uses: ./.github/actions/version-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pat_token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          version_file: "version.txt"
          branch: "main"

      ###########################################
      # TOKENIZED AUTO COMMIT
      ###########################################
      - name: New Commit
        if: github.event.pull_request.merged == true
        uses: ./.github/actions/auto-commit
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          version_file: "version.txt"
          new_version: ${{ steps.version.outputs.new_version }}
          new_tag_version: ${{ steps.version.outputs.new_tag_version }}
          branch: "main"

      ###########################################
      # BUILD
      ###########################################
      - name: Build a new APK / AAP
        run: echo "Build"

      ###########################################
      # PRODUCTION TRACK UPLOAD
      ###########################################
      - name: Production Track Upload
        run: echo "Production Track Upload"
