---
name: Staging Workflow

on:
  pull_request:
    branches:
      - staging
    types:
      - "closed"
  workflow_dispatch:

concurrency:
  group: staging-versioning-and-build
  cancel-in-progress: false

jobs:
  version-build-internal:
    name: Staging - Version Bump, Build, and Internal
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ###########################################
      # VERSION BUMP
      ###########################################
      - name: Bump version based on PR labels
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        id: version
        uses: ./.github/actions/version-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pat_token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          version_file: "version.txt"
          branch: "staging"

      ###########################################
      # TOKENIZED AUTO COMMIT
      ###########################################
      - name: New Commit
        if: github.event.pull_request.merged == true && !contains(join(github.event.pull_request.labels.*.name, ','), 'no-build')
        uses: ./.github/actions/auto-commit
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          version_file: "version.txt"
          new_version: ${{ steps.version.outputs.new_version }}
          new_tag_version: ${{ steps.version.outputs.new_tag_version }}
          branch: "staging"         

      ###########################################
      # BUILD
      ###########################################
      - name: Build a new APK / AAP
        run: echo "Build"

      ###########################################
      # INTERNAL TRACK UPLOAD
      ###########################################
      - name: Internal Track Upload
        if: |
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
          (github.event_name == 'push' && github.event.pull_request == null)
        run: echo "Internal Track Upload"
