---
name: Staging Workflow

on:
  pull_request:
    branches:
      - staging
      - main
  push:
    branches:
     - staging
  workflow_dispatch:

concurrency:
  group: staging-versioning-and-build
  cancel-in-progress: false

jobs:
  lint-test-report:
    name: Staging - Version Bump
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ###########################################
      # VERSION BUMP
      ###########################################
      - name: Bump version based on PR labels
        uses: ./.github/actions/version-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_file: "version.txt"

      ###########################################
      # COMMIT NEW VERSION
      ###########################################
      # - name: Auto commit new pubspec version
      #   id: auto-commit-action
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     commit_message: "Bump pubspec version to ${{ env.new_version }}"
      #     file_pattern: "apps/multichoice/pubspec.yaml"
      #     disable_globbing: true
